config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/admin/dashboard')
    get  "admin/dashboard" => "admin/dashboard#index", :as => 'user_root' # after sign in on admin page
    devise_for :users

    namespace :admin do
      get '/', :to => redirect('/admin/dashboard')

      resources :students
      resources :teachers
      resources :departments
    end

end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :students
    has_many :teachers
end

app/models/kc.rb
class Kc < ActiveRecord::Base
end

app/models/stu_score.rb
class StuScore < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_one :department
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_one :department
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

         rolify
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  
  layout 'admin'
  before_action :authenticate_user!
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/kcs_controller.rb
class Admin::KcsController < Admin::BaseController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController <  Admin::BaseController
  def index
    @stus = Student.all
  end
  def new
    @stu = Student.new
    @de = Department.all
  end
  def create
    @stu = Student.new(stu_params)
    @stu.save
    redirect_to :action => 'index'
  end
  def edit
    @stus = Student.find(params[:id])
    @dep = Department.all
  end
  def update
    @stus = Student.find(params[:id])
    @stus.update(stu_params)
    redirect_to :action => 'index'
  end
  def destroy
    @stus =Student.find(params[:id])
    @stus.destroy
    redirect_to :action => 'index'
  end
  def stu_params
    params.require(:student).permit!
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::BaseController
  def index
    @teas = Teacher.all
  end
  def new
    @tea = Teacher.new
    @de = Department.all
  end
  def create
    @tea = Teacher.new(tea_params)
    @tea.save
    redirect_to :action => 'index'
  end

  def edit
    @teas = Teacher.find(params[:id])
    @dep = Department.all
  end
  def update
    @teas = Teacher.find(params[:id])
    @teas.update(tea_params)
    redirect_to :action => 'index'
  end
  def destroy
    @teas =Teacher.find(params[:id])
    @teas.destroy
    redirect_to :action => 'index'
  end
  def tea_params
    params.require(:teacher).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kc_helper.rb
module KcHelper
end

app/helpers/stu_score_helper.rb
module StuScoreHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/admin/kcs/create.html.erb
<h1>Kc#create</h1>
<p>Find me in app/views/kc/create.html.erb</p>

app/views/admin/kcs/index.html.erb
<h1>Kc#index</h1>
<p>Find me in app/views/kc/index.html.erb</p>

app/views/admin/kcs/new.html.erb
<h1>Kc#new</h1>
<p>Find me in app/views/kc/new.html.erb</p>

app/views/admin/students/create.html.erb
<h1>Student#create</h1>
<p>Find me in app/views/student/create.html.erb</p>

app/views/admin/students/edit.html.erb
<%= form_for [:admin, @stus] do |f| %>
  <table> <p>
  <tr><td><%=f.label :编号%></td>
  <td><%= f.text_field :id%></tr>
  <tr><td><%=f.label :名字%></td>
  <td><%= f.text_field :name%></tr>
  <tr><td><%=f.label :年龄%></td>
  <td><%= f.text_field :age%></tr>
  <tr><td><%=f.label :性别%></td>
  <td><%=f.select :sex,[["女",1],["男",0]] %></tr>
  <tr><td> <%= f.label :系部 %></td>
  <td><%=f.select :departmentNo, (@dep.collect { |s| [s.dename,s.id] } )%></td></tr>
    <tr><td> <%=f.submit "提交"%></td></tr>
  </p>
  </table>
<% end -%>

app/views/admin/students/index.html.erb
<table class="table table-striped">

  <tr>
    <td>编号</td>
    <td>名称</td>
    <td>年龄</td>
    <td>性别</td>
    <td>部系</td>
    <td>操作</td>
  </tr>

  <% @stus.each do|ar| %>
      <tr>
        <td><%=ar.id%></td>
        <td><%=ar.name%></td>
        <td><%=ar.age%></td>
        <td><% if(ar.sex == 0) %><p>男</p><% end %><% if(ar.sex == 1) %><p>女</p><% end %></td>
        <td><%=Department.find(ar.departmentNo).dename %></td>
        <td>
          <%=link_to "删除", {:controller=>:students,:action=>:destroy, :id=>ar}, :method=>:delete  %>|
          <%=link_to "修改", edit_admin_student_path(ar) %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/students/new.html.erb
<%=form_for(@stu,url: {:controller => 'students',:action =>'create' },html:{method: :post})do|f| %>
    <p>
      <%= f.label :姓名 %>
      <%= f.text_field :name, size: 12%>
      <%= f.label :年龄 %>
      <%= f.text_field :age, size: 8%>
      <%= f.label :性别 %>
      <%= f.select :sex,[["女",1],["男",0]] %>
      <%= f.label :系部 %>
      <%= f.select :departmentNo, (@de.collect { |p| [p.dename,p.id] } )%>
    </p>
    <p>
      <%=f.submit "提交"%>
    </p>
<% end %>

app/views/admin/teachers/create.html.erb
<h1>Teacher#create</h1>
<p>Find me in app/views/teacher/create.html.erb</p>

app/views/admin/teachers/edit.html.erb
<%= form_for [:admin, @teas] do |f| %>
  <table> <p>
  <tr><td><%=f.label :编号%></td>
  <td><%= f.text_field :id%></tr>
  <tr><td><%=f.label :名字%></td>
  <td><%= f.text_field :tname%></tr>
  <tr><td><%=f.label :性别%></td>
  <td><%=f.select :tsex,[["女",1],["男",0]] %></tr>
  <tr><td> <%= f.label :系部 %></td>
  <td><%=f.select :tdepartmentNo, (@dep.collect { |s| [s.dename,s.id] } )%></td></tr>
    <tr><td> <%=f.submit "提交"%></td></tr>
  </p>
  </table>
<% end -%>

app/views/admin/teachers/index.html.erb
<table class="table table-striped">

  <tr>
    <td>编号</td>
    <td>名称</td>
    <td>性别</td>
    <td>部系</td>
    <td>操作</td>
  </tr>

  <% @teas.each do|ar| %>
      <tr>
        <td><%=ar.id%></td>
        <td><%=ar.tname%></td>
        <td><% if(ar.tsex == 0) %><p>男</p><% end %><% if(ar.tsex == 1) %><p>女</p><% end %></td>
        <td><%=Department.find(ar.tdepartmentNo).dename %></td>
        <td>
          <%=link_to "删除", {:controller=>:teachers,:action=>:destroy, :id=>ar}, :method=>:delete  %>|
          <%=link_to "修改", edit_admin_teacher_path(ar) %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/teachers/new.html.erb
<%=form_for(@tea,url: {:controller => 'teachers',:action =>'create' },html:{method: :post})do|f| %>
    <p>
      <%= f.label :姓名 %>
      <%= f.text_field :tname, size: 10%>
      <%= f.label :性别 %>
      <%= f.select :tsex,[["女",1],["男",0]] %>
      <%= f.label :系部 %>
      <%= f.select :tdepartmentNo, (@de.collect { |p| [p.dename,p.id] } )%>
    </p>
    <p>
      <%=f.submit "提交"%>
    </p>
<% end %>