config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/admin/dashboard')
    get  "admin/dashboard" => "admin/dashboard#index", :as => 'user_root' # after sign in on admin page
    devise_for :users

    namespace :admin do
      get '/', :to => redirect('/admin/dashboard')

      resources :students
      resources :teachers
      resources :departments
    end

end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :students
    has_many :teachers
end

app/models/kc.rb
class Kc < ActiveRecord::Base
end

app/models/stu_score.rb
class StuScore < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_one :department
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_one :department
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

         rolify
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  
  layout 'admin'
  before_action :authenticate_user!
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::BaseController
  def index
    @deps = Department.all
  end

  def new
    @dep = Department.new
  end

  def create
    @dep = Department.new(dep_params)
    @dep.save
    redirect_to  :action => 'index'
  end

  def edit
    @deps = Department.find(params[:id])

  end

  def update
    @deps = Department.find(params[:id])
    @deps.update(dep_params)
    redirect_to :action => 'index'
  end
  def destroy
    @deps =Department.find(params[:id])
    @deps.destroy
    redirect_to :action => 'index'
  end

  def dep_params
    params.require(:department).permit!
  end
end

app/controllers/admin/kcs_controller.rb
class Admin::KcsController < Admin::BaseController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController <  Admin::BaseController
  def index
    @stus = Student.all
  end
  def new
    @stu = Student.new
    @de = Department.all
  end
  def create
    @stu = Student.new(stu_params)
    @stu.save
    redirect_to :action => 'index'
  end
  def edit
    @stus = Student.find(params[:id])
    @dep = Department.all
  end
  def update
    @stus = Student.find(params[:id])
    @stus.update(stu_params)
    redirect_to :action => 'index'
  end
  def destroy
    @stus =Student.find(params[:id])
    @stus.destroy
    redirect_to :action => 'index'
  end
  def stu_params
    params.require(:student).permit!
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::BaseController
  def index
    @teas = Teacher.all
  end
  def new
    @tea = Teacher.new
    @de = Department.all
  end
  def create
    @tea = Teacher.new(tea_params)
    @tea.save
    redirect_to :action => 'index'
  end

  def edit
    @teas = Teacher.find(params[:id])
    @dep = Department.all
  end
  def update
    @teas = Teacher.find(params[:id])
    @teas.update(tea_params)
    redirect_to :action => 'index'
  end
  def destroy
    @teas =Teacher.find(params[:id])
    @teas.destroy
    redirect_to :action => 'index'
  end
  def tea_params
    params.require(:teacher).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kc_helper.rb
module KcHelper
end

app/helpers/stu_score_helper.rb
module StuScoreHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/admin/departments/create.html.erb
<%=form_for(@dep,url: {:controller => 'departments',:action =>'create' },html:{method: :post})do|f| %>
    <p>
      <%= f.label :名称 %>
      <%= f.text_field :dename%>
    </p>
    <p>
      <%=f.submit "提交"%>
    </p>
<% end %>

app/views/admin/departments/edit.html.erb
<%= form_for [:admin, @deps] do |f| %>
  <table> <p>
  <tr><td><%=f.label :编号%></td>
  <td><%= f.text_field :id%></tr>
  <tr><td> <%= f.label :系部 %></td>
  <td><%= f.text_field :dename%></td></tr>
  </p>
  <p>
    <tr><td> <%=f.submit "提交"%></td></tr>
  </p>
  </table>
<% end -%>

app/views/admin/departments/index.html.erb
<table class="table table-striped" style="width:800px">

  <tr>
    <td>编号</td>
    <td>名称</td>
    <td>操作</td>
  </tr>
  <% @deps.each do|ar| %>
      <tr>
        <td><%=ar.id%></td>
        <td><%=ar.dename%></td>
        <td>
          <%=link_to "删除", {:controller=>:departments,:action=>:destroy, :id=>ar}, :method=>:delete  %>|
          <%=link_to "修改", edit_admin_department_path(ar) %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/departments/new.html.erb
<%= form_for @dep, url: admin_departments_path do |f| %>
  <p>
    <%= f.label :名称 %><br>
    <%= f.text_field :dename %>
  </p>
  <p>
    <%= f.submit :提交 %>
  </p>
<% end %>